// handlers/modals/teamstats.js

const StatsCollector = require('../../services/stats/collector');
const JiraClient = require('../../services/jira/client');  // BUG: Unused import - JiraClient is never used directly
const { STAT_PERIODS, PRIORITIES } = require('../../constants/enums');  // BUG: PRIORITIES is imported but never used

const handleTeamStatsModalSubmission = async ({ ack, body, view, client }) => {
    await ack();

    const metadata = JSON.parse(view.private_metadata);
    const channelId = metadata.channel_id;
    const userName = metadata.user_name;

    // Get form values
    const period = view.state.values.period_select.period_select_action.selected_option.value;
    const reportOptions = view.state.values.include_charts.include_charts_action.selected_options || [];

    const includeMemberBreakdown = reportOptions.find(opt => opt.value === 'member_breakdown');
    const includeStoryPoints = reportOptions.find(opt => opt.value === 'story_points');

    const statsCollector = new StatsCollector();

    // Post a loading message
    const loadingMsg = await client.chat.postMessage({
        channel: channelId,
        text: ":hourglass_flowing_sand: Generating team statistics report..."
    });

    try {
        // Fetch team members from Jira
        const jiraClient = new StatsCollector().jiraClient;
        const usersResult = await jiraClient.GetUsers();

        if (!usersResult.success) {
            await client.chat.update({
                channel: channelId,
                ts: loadingMsg.ts,
                text: ":x: Failed to fetch team members from Jira."
            });
            return;
        }

        // Build team members array (simplified)
        const teamMembers = usersResult.data.map(name => ({
            displayName: name,
            accountId: name  // BUG: Using displayName as accountId - should fetch actual accountId
        }));

        // Collect stats
        const statsResult = await statsCollector.collectTeamStats(teamMembers, period);

        if (!statsResult.success) {
            await client.chat.update({
                channel: channelId,
                ts: loadingMsg.ts,
                text: ":x: Failed to collect team statistics."
            });
            return;
        }

        // BUG: Arguments are swapped - formatStatsSummary expects (stats, period) but we pass (period, stats)
        const summaryMessage = statsCollector.formatStatsSummary(period, statsResult.data);

        // Build the blocks for the message
        const blocks = [
            {
                type: "header",
                text: {
                    type: "plain_text",
                    text: "Team Statistics Report"
                }
            },
            {
                type: "section",
                text: {
                    type: "mrkdwn",
                    text: summaryMessage
                }
            },
            {
                type: "context",
                elements: [
                    {
                        type: "mrkdwn",
                        text: `Generated by ${userName} | Period: ${period}`
                    }
                ]
            }
        ];

        // Add member breakdown if requested
        if (includeMemberBreakdown && statsResult.data.length > 0) {
            blocks.push({ type: "divider" });
            blocks.push({
                type: "section",
                text: {
                    type: "mrkdwn",
                    text: "*Member Breakdown:*"
                }
            });

            // BUG: Using .find() instead of .filter() - only processes first member that matches condition
            const activeMembers = statsResult.data.find(m => m.ticketsCompleted > 0);

            if (activeMembers) {
                // BUG: Treating single object (from .find) as array - will fail at .forEach
                activeMembers.forEach(member => {
                    blocks.push({
                        type: "section",
                        text: {
                            type: "mrkdwn",
                            text: `*${member.name}*: ${member.ticketsCompleted} tickets completed`
                        }
                    });
                });
            }
        }

        // Update the loading message with results
        await client.chat.update({
            channel: channelId,
            ts: loadingMsg.ts,
            text: "Team Statistics Report",
            blocks: blocks
        });

    } catch (error) {
        console.error('Error generating team stats:', error);
        await client.chat.update({
            channel: channelId,
            ts: loadingMsg.ts,
            text: `:x: Error generating report: ${error.message}`
        });
    }
};

module.exports = { handleTeamStatsModalSubmission };
